# Generated by Django 2.0.13 on 2019-04-17 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_no', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='job_no',
            new_name='JobNo',
        ),
    ]
