# Generated by Django 2.0.13 on 2019-04-15 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cutter',
            fields=[
                ('cutter_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('cutter_id', models.IntegerField()),
                ('cutter_in_draw', models.IntegerField()),
            ],
        ),
    ]
