# Generated by Django 2.0.13 on 2019-04-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutter',
            name='add_cutter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cutter',
            name='job_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cutter',
            name='sub_cutter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='cutter_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cutter',
            name='cutter_in_draw',
            field=models.IntegerField(default=0),
        ),
    ]
