# Generated by Django 2.0.13 on 2019-04-17 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutters', '0002_auto_20190416_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutter',
            name='job_no',
        ),
    ]
